### ISSUE TITLE
High-level API design

### ISSUE THREAD

**Issue by monkeypants** [hipfish/hipfish-api-docs#2]
HiPFiSH is, in essence, a CDN. The different between HiPFiSH and other CDNs is that we publish files with IPFS (as opposed to only HTTP/HTTPS).

We need an API so our customers can manage their resources which we host.before we design it, we should examine other public CDN APIs and figure out what we like/dislike about them.

We should also remain mindful of the differences between an IPFS CDN and a HTTP/HTTPS one:

 * HTTP/HTTPS CDN's proxy an upstream resource. IPFS is a little more complicated, the resource may or may not be available upstream; there is more than one way to get it, we need an intermediate "archive" concept.
 * IPFS has strong opinions about resource names

**Comment by monkeypants** [comment]
Archived/published files should be organised in named collections.

Post/put/delete should operate on collections, not individual files.

Get collection should indicate status of individual files.

Policy settings (disposal date, privacy lock, HTTPS publication, etc) should be per collection, not per individual file.

**Comment by monkeypants** [comment]
Traditional cdn has policy around changes to upstream files. With ipfs, a changed file is a different address.

If we add a URL to a hosted collection, it will be downloaded once, archived, then hosted as it's content-address. At that point, we will have immutable hosted content.

Do we want a feature that checks a URL periodically and, if changed, downloads and hosts it? Could this be a feature that follows links? I mean, automatically-host-all-files-that-this-page-links-to? It could ping the page at scheduled interval, download all files it links to, calculate their content-address, and add it to the collection if not already present.

**Comment by monkeypants** [comment]
I still think we are missing a concept like "collection". I think we will end up with similar pattern to github.

account > collection > resource

 * user (account - maybe like personal or organisation) has multiple "collections"
 * collection has specific config: publish or archive only (privacy lock), publish until date, renew publishing, etc.
 * The billing is organised by user (billing period) > collection > time, so users can see how much each collection cost in the billing period (storage + traffic)
 * logging includes collection > resource
 * a resource belongs to a collection.
 * a resource can be a file or a folder
 
I think if we had this structure, we would end up with organistions and memberships and teams and all that stuff too. But we could add that later. It would be more difficult to add collections later I think though, because the API would have to change a lot.

thoughts?

**Comment by koriaf** [comment]
API would change a lot if we put collection in the REST URLs. And we probably shall.

I like github-like workflow.

So let's assume that specific access keys identify user/account in API, and we must prefix any request by collection (or shall we call it bucket?).
Examples:
POST `/api/v0/defaultbucket/upload/` - create new item in collection, multipart/form-data format
POST `/api/v0/defaultbucket/ipfs/` - create new item in collection, json format with IPFS hash provided

both return job UUID, and we can trade job UUID to file IPFSHASH at some point

GET `/api/v0/defaultbucket/Qmlalala/` - file info, where value is file UUID
DELETE `/api/v0/defaultbucket/Qmlalala/` - remove that file
POST `/api/v0/defaultbucket/Qmlalala/publish/` - publish file
POST `/api/v0/defaultbucket/Qmlalala/unpublish/` - remove file from IPFS publication
and so on.

There is problem with the directories. But it can be solved by replacing Qmlalala by UUID of item. And in turn item may have the hash (directory, which is published to IPFS, or any file), or may not (directory never published to IPFS).

So GET `/api/v0/defaultbucket/31422418-433f-49df-9141-885ef633ee97/` gives us response like:
```
{
    "Type": "directory",
    "links": [list of children UUID],
   ...
}
```

**Comment by monkeypants** [comment]
Bucket word is OK too. I actually put it in my comment above then changed it to "collection", either is fine.

I agree with /api/v0/* base path and use of guids

I think `/api/v0/buckets/{id}/` is better than "defaultbucket"

bucket will never have ipfs address, because it's a changable thing. User can add/delete resources to bucket. The resource has the ipfs hash, it is the file or (immutable) directory. Maybe one day bucket could have IPNS address, but not now (currently a single IPFS serve uses hash of its key for it's IPNS address, so only one address per server and only one server per address). Does that clear up the problem with directories?

GET `/api/v0/buckets/31422418-433f-49df-9141-885ef633ee97/ would give something like:
```
{
    "resuorces": [list of children IPFS addresses],
   ...
}
```

and POST `/api/v0/resources/` would need to know what bucket to post to

and GET `/api/v0/resources/&bucket=31422418-433f-49df-9141-885ef633ee97/` would give you the same information as the GET bucket query...

**Comment by koriaf** [comment]
If we assume that any object has it's own bucket when it's safe to say that we can prefix bucket ID to any request.
POST /api/v0/bucketname/resources/ or POST /api/v0/bucket/7777/resources/

**Comment by koriaf** [comment]
My current vision is:
```
Prefix: /api/archive/v0/

GET / - return list of buckets and virtual root filesystem (what do you have on UI now)

POST /file/ - create new file in temp storage
    multipart/form-data with file content and file metadata (filename, directory where to put it, etc)
    return IPFS hash and newly created file UUID (id)
POST /file/ipfs - create new file upload task by IPFS
POST /file/whatever - create new file upload task by other way (where whatever replaces to S3, HTTP and so on)
    metadata for these requests: directory (null for root directory)
    return task UUID, which can be traded later to file UUID and file IPFS hash.

GET /job/{uuid}/ - get information about pending job from POST /file/ipfs or /file/s3, etc
    if job still in progres: {'status': 'uploading'}
    if done: {'status': 'done', 'item_uuid': 'xxx-xxx', 'item_ipfs': 'Qmlalala or null', 'type': 'file|directory'}

POST /directory/ - create new directory in temporary storage, not in bucket
    metadata: directory readable name

Buckets:
POST /bucket/ - create new bucket with given metadata
    metadata: bucket readable name, 'private' flag (default = false)
GET /bucket/{id}/ - get bucket info by ID with files and subdirectories
PATCH /bucket/{id}/ - update bucket metadata (private/public lock, store till, etc)
DELETE /bucket/{id}/ - drop the bucket completely, async op
GET /bucket/{id}/{file or directory ID or IPFS hash}/ - get info about the item
GET /bucket/{id}/{file or directory ID or IPFS hash}/data - fetch file data as stream or directory data as tar archive

Directories and files in temp storage:
GET /item/{id}/ - get directory or file info (metadata, files, subdirectories), works for subdirectories
GET /item/{id}/data - download the file (stream) or directory (tar)
GET /item/{id}/move - move item from it's current location in temporary place to the directory or the bucket
      `directory` is filled, move to this directory in temp storage
POST /item/{id}/bucketize - publish item to given bucket (bucket in payload)
DELETE /item/{id}/ - delete the item (recursive if directory)
```

**Comment by monkeypants** [comment]
must we have ../archive/.. in the prefix? I don't see how it makes things better.

I agree with `GET /`, `POST /file/*` and `GET /job/{uuid}`

for `POST /directory/`, I think I am unhappy with the word directory. Can we call it "stage" instead?

I agree with `POST /bucket/`, `* /bucket/{id}/` and `GET /bucket/{id}/*`. Maybe "rename" is more user-friendly than "move". For unix friends, maybe they are synonyms :) Maybe "archive" is more user-friendly than "bucketize" (although maybe make that an undocumented synonym, easter-egg).

for `* /item/{id}/*`, this is a bit confusing. how did you see this relating to `/stage/{id}/`?

**Comment by koriaf** [comment]
Item ID is unique, so we can avoid usage of bucket name in URLs because bucket can be strictly determined by the item ID (any item has foreginkey to bucket or None if there is no bucket yet).

remove /archive/ from api - agreed.

item here may be both directory and file. If you think we can rename 'item' to 'stage' then let's try it. It's easy to change naming, now we just need to understand how it works in general.

**Comment by monkeypants** [comment]
I wanted to rename `/directories/` to `/stage/`. Is `/item/` same or different to directories/stage?

**Comment by koriaf** [comment]
item = directory or file. both have unique UUID and, when published, IPFS hash.
please note that directory may have subdirectory or subfiles, and subdirectories may have subitems as well. It would look strange when stage aaa have 2 stages bbb and ccc and single file xxx.

**Comment by koriaf** [comment]
How to get subdirectory:
```
get /item/aaa/ -> see bbb and ccc and xxx
get /item/ccc/ -> see content of ccc subdirectory
get /item/xxx/ -> see metadataa about xxx file
get /item/xxx/data - fetch file content
```

**Comment by monkeypants** [comment]
if directory contains `foo/bar/baz.txt` (etc - nested content), then why not `GET /items/{id}/data/foo/bar/baz.txt` ?

**Comment by koriaf** [comment]
It requires files to have some readable non-duplicated name (which is probably a sane requirement).
And if you want filename in urls then we shall move any verb to beginning from end (metadata, body). Like:
```
GET /stage/metadata/foor/bar/baz.txt
GET /stage/metadata/foor/bar/
GET /stage/body/foor/bar/baz.txt
GET /stage/body/foor/bar/
DELETE /stage/foo/bar/baz.txt
DELETE /stage/foo/bar/ (recursive one)
PATCH /stage/metadata/foo/bar/baz.txt (if anything to update here)

POST /stage/move/foo/bar/baz.txt?target=/for/file.txt
```

Prefix `/stage/` changes to `/bucket/{bucket-id-or-name}/` for files in bucket.

**Comment by monkeypants** [comment]
There is something about this that I don't understand. Is this right:

 * `/items/{id}/` is a file or a directory.
 * `/stage/{id}/foo/` is a file or directory.
 * `/buckets/{id}/` is a bucket, 
 * `/buckets/{id}/foo` is either a file or a directory, it's name is an IPFS hash, it can not be edited but it can be deleted.
 * `GET /buckets/{id}/foo` returns data about the item foo in my bucket
 * `GET /buckets/{id}/foo/data` contains either a directory listing or the contents of the foo file
 * `GET /buckets/` returns a list of my buckets, and tells me their unique (in my account) human names as well as their UUID
 * `GET /buckets/{id}/` returns a list of the things in my bucket, including their IPFS hash names

**Comment by koriaf** [comment]
* `/buckets/{id}/foo` - we can accept UUID (database row uuid) or IPFS hash or full filename here. it's all same for us.
* GET /buckets/{id}/foo/data returns either a file content or error for directory (directory files are placed in metadata)

and if we want `foo` to be path then we shall move verb (`/data`) to the beginning (`/buckets/{bucket_id}/data/{file_id}/`)

Generally speaking, I would like `foo` to be "Any identifier known to you". It would easy the API usage. so we can accept both UUID of database row (the thing any file and directory always have), the QmHash (the thing only some of the objects always have) or fullpath (unique for bucket or stage).

**Comment by monkeypants** [comment]
> QmHash (the thing only some of the objects always have)

Why don't all things have one? even if we don't publish it, or the bucket is "privacy locked" (unable to publish), every file or directory must be hashed, right? I thought the hash was our ID?

**Comment by koriaf** [comment]
1) we can't offer directories hash on stage (would change too much)
2) it's good to keep it consistent - we told them "use whatever uniq you want" for stage and it works for bucket.

But your way is also good, when we use IPFS hash for the object in bucket it would be so strict and solid. I don't know what to choose.
But we can't use IPFS hash for directories in stage, and this is the biggest problem now, so we have to support UUIDs or readable names anyway.

And ipfs hashes are unreadable, unlike readable names.

**Comment by monkeypants** [comment]
nothing has hash in stage (yet), because stage is mutable. everything in bucket has hash, because things in bucket are immutable.

Names of things (for UI and "name" attribute in json) does not need to be in URL, UUID or Qmhash (might not always be "Qm", but that's easier to type than "IPFS Hash") is good.

The API/URL does not need to be readable, it has to be developer friendly. I think that means the logic of needs to be clear, more than the tokens do.

One reason to use UUIDs rather than Qmhash the Qmhash is longer. If we have to support `/buckets/{uuid}/{Qmhash}/data/some/long/path`, it will reduce the size of the path we can handle. I wonder if this is still a real problem?

Maybe it would be better to use UUIDs everywhere? if we had user in the path, we could use slugs of names for buckets, but two buckets might contain different directories with the same name.

**Comment by koriaf** [comment]
We don't have to put user in path, because user can access only it's own bucket based on authentication. So usage of bucket slugs are completely harmless.

Let's start from uuids for files and slugs for buckets, and we will see what is handy for us and what is not.

**Comment by monkeypants** [comment]
but the problem with bucket slugs in path is that they are unique. Two different users might want to have a bucket called "correspondence-2017-01". They should be able to, that's why UUID is good for buckets.

**Comment by koriaf** [comment]
and they want to share it between each other?
first user retrieves /bucket/correspondence-2017-01/ and gets his own bucket.
second user tries to get it and get 404 if he doesn't have such bucket or get's his bucket if he has created it. 

imagine it as /userid/ prefix for any request, because we pass authorization token with each request.

We can start have problems only when buckets can be accessed by different users (user1 can allow user2 to see his bucket). If we plan it then yes, it's better to use the UUID everywhere.

**Comment by monkeypants** [comment]
I'm pretty sure UUID is better, because I think different users will want to use the same name.

**Comment by koriaf** [comment]
Okay. To be honest, current implementation of done endpoints support both - first it looks by UUID, then it looks by some readable name.
So, if we assume that any ID in URL or payload is UUID then we are safe.

**Comment by monkeypants** [comment]
Are we ready for swagger.yaml ?

**Comment by koriaf** [comment]
yes, I can start documenting current endpoints (and desired/todo), but this spec will change completely several times.
But swagger might be easier to work on than github task, this one is too long already.

**Comment by monkeypants** [comment]
ok, close this ticket when we have first draft of swagger in the repo, after that it can be new tickets...
